# Helped me define the syntax workflow of the yml file below 
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# workflow name Optional
name: Build and Deploy

# these events trigger workflow
on:
  # pushs to the repo
  push:
    branches:
      - main
  # Pull request
  pull_request:
    branches:
      - '*'

#Groups together all the jobs which run together in the repo
jobs:
  build:
    #excutes a VM hosted by GitHub, configues to run on latest version of Ubuntu Linux runner.1
    runs-on: ubuntu-latest
    #Groups steps to be run
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        #this step insures python is installed
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install the dependencies
        #using pip to install some software
        run: |
          python -m pip install -r requirements.txt
      - name: Build the JupyterLite site
        run: |
          jupyter lite build --contents content --output-dir dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    #use permissions to change origninal permissions
    permissions:
      pages: write
      id-token: write

    #when the workflow runs the jobs will be subject to any rules in the enviroment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # same as .1 runs a self contained host to create a highly custom environment for the user
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
